class ResponseData{
static var jsonData ={
  "states":[
    {
      "statename":"Tamilnadu",
      "id":"1",
      "cities":[
        {
          "name":"Chennai",
          "id":"tn1",
          "areas":[
            {
              "name":"AnnaNagar",
              "id":"C1",
              "pincode":[
                {
                  "pc":"600075"
                },
                {
                  "pc":"600076"
                },
                {
                  "pc":"600077"
                }
              ]
            },
            {
              "name":"KKNagar",
              "id":"C2",
              "pincode":[
                {
                  "pc":"600109"
                },
                {
                  "pc":"600111"
                },
                {
                  "pc":"600112"
                },
                {
                  "pc":"600115"
                }
              ]
            },
            {
              "name":"T-Nagar",
              "id":"C3",
              "pincode":[
                {
                  "pc":"600003"
                }
              ]
            },
            {
              "name":"BesantNagar",
              "id":"C4",
              "pincode":[
                {
                  "pc":"600109"
                },
                {
                  "pc":"600111"
                }
              ]
            }
          ]
        },
        {
          "name":"Trichy",
          "id":"tn2",
          "areas":[
            {
              "name":"BigBazaarStreet",
              "id":"T1",
              "pincode":[
                {
                  "pc":"617075"
                },
                {
                  "pc":"617076"
                },
                {
                  "pc":"617077"
                }
              ]
            },
            {
              "name":"KKNagar",
              "id":"T2",
              "pincode":[
                {
                  "pc":"617109"
                },
                {
                  "pc":"617111"
                },
                {
                  "pc":"617112"
                },
                {
                  "pc":"617115"
                }
              ]
            },
            {
              "name":"Thurayur",
              "id":"T3",
              "pincode":[
                {
                  "pc":"617003"
                }
              ]
            },
            {
              "name":"Manaparai",
              "id":"T4",
              "pincode":[
                {
                  "pc":"617109"
                },
                {
                  "pc":"617111"
                }
              ]
            }
          ]
        },
        {
          "name":"Dindigul",
          "id":"tn3",
          "areas":[
            {
              "name":"EastGovindapuram",
              "id":"D1",
              "pincode":[
                {
                  "pc":"624075"
                },
                {
                  "pc":"624076"
                },
                {
                  "pc":"624077"
                }
              ]
            },
            {
              "name":"R.M.Colony",
              "id":"D2",
              "pincode":[
                {
                  "pc":"624009"
                },
                {
                  "pc":"624011"
                },
                {
                  "pc":"624012"
                },
                {
                  "pc":"624015"
                }
              ]
            },
            {
              "name":"SocietyStreet",
              "id":"D3",
              "pincode":[
                {
                  "pc":"624003"
                }
              ]
            },
            {
              "name":"ArivuThiruKovil",
              "id":"D4",
              "pincode":[
                {
                  "pc":"624009"
                },
                {
                  "pc":"624011"
                }
              ]
            }
          ]
        },
        {
          "name":"Madurai",
          "id":"tn4",
          "areas":[
            {
              "name":"MeenakshiStreet",
              "id":"M1",
              "pincode":[
                {
                  "pc":"625075"
                },
                {
                  "pc":"625076"
                },
                {
                  "pc":"625077"
                }
              ]
            },
            {
              "name":"Vilakuthoon",
              "id":"M2",
              "pincode":[
                {
                  "pc":"625009"
                },
                {
                  "pc":"625011"
                },
                {
                  "pc":"625012"
                },
                {
                  "pc":"625015"
                }
              ]
            },
            {
              "name":"Paravai",
              "id":"M3",
              "pincode":[
                {
                  "pc":"625003"
                }
              ]
            },
            {
              "name":"Samayanallur",
              "id":"M4",
              "pincode":[
                {
                  "pc":"625009"
                },
                {
                  "pc":"625011"
                }
              ]
            }
          ]
        },
        {
          "name":"Coimbatore",
          "id":"tn5",
          "areas":[
            {
              "name":"SaiBabaColony",
              "id":"CO1",
              "pincode":[
                {
                  "pc":"641075"
                },
                {
                  "pc":"641076"
                },
                {
                  "pc":"641077"
                }
              ]
            },
            {
              "name":"Saravanampatti",
              "id":"CO2",
              "pincode":[
                {
                  "pc":"641009"
                },
                {
                  "pc":"641011"
                },
                {
                  "pc":"641012"
                },
                {
                  "pc":"641015"
                }
              ]
            },
            {
              "name":"Kuniyamuthur",
              "id":"CO3",
              "pincode":[
                {
                  "pc":"641003"
                }
              ]
            },
            {
              "name":"B.K.Pudhur",
              "id":"CO4",
              "pincode":[
                {
                  "pc":"641009"
                },
                {
                  "pc":"641011"
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "statename":"Kerala",
      "id":"2",
      "cities":[
        {
          "name":"Kochi",
          "id":"kl1",
          "areas":[
            {
              "name":"Mattenchery",
              "id":"KLKO1",
              "pincode":[
                {
                  "pc":"500075"
                },
                {
                  "pc":"500076"
                },
                {
                  "pc":"500077"
                }
              ]
            },
            {
              "name":"FortKochi",
              "id":"KLKO2",
              "pincode":[
                {
                  "pc":"500109"
                },
                {
                  "pc":"500111"
                },
                {
                  "pc":"500112"
                },
                {
                  "pc":"500115"
                }
              ]
            },
            {
              "name":"Kalamssary",
              "id":"KLKO3",
              "pincode":[
                {
                  "pc":"500003"
                }
              ]
            },
            {
              "name":"Tripunithura",
              "id":"KLKO4",
              "pincode":[
                {
                  "pc":"500109"
                },
                {
                  "pc":"500111"
                }
              ]
            }
          ]
        },
        {
          "name":"Ernakulam",
          "id":"kl2",
          "areas":[
            {
              "name":"Paravur",
              "id":"KLE1",
              "pincode":[
                {
                  "pc":"517075"
                },
                {
                  "pc":"517076"
                },
                {
                  "pc":"517077"
                }
              ]
            },
            {
              "name":"Aluva",
              "id":"KLE2",
              "pincode":[
                {
                  "pc":"517109"
                },
                {
                  "pc":"517111"
                },
                {
                  "pc":"517112"
                },
                {
                  "pc":"517115"
                }
              ]
            },
            {
              "name":"Kuttanad",
              "id":"KLE3",
              "pincode":[
                {
                  "pc":"517003"
                }
              ]
            },
            {
              "name":"Muvattupuzha",
              "id":"KLE4",
              "pincode":[
                {
                  "pc":"517109"
                },
                {
                  "pc":"517111"
                }
              ]
            }
          ]
        },
        {
          "name":"Alleppye",
          "id":"kl3",
          "areas":[
            {
              "name":"Karumadi",
              "id":"KLA1",
              "pincode":[
                {
                  "pc":"524075"
                },
                {
                  "pc":"524076"
                },
                {
                  "pc":"524077"
                }
              ]
            },
            {
              "name":"Alappuzha Beach",
              "id":"KLA2",
              "pincode":[
                {
                  "pc":"524009"
                },
                {
                  "pc":"524011"
                },
                {
                  "pc":"524012"
                },
                {
                  "pc":"524015"
                }
              ]
            },
            {
              "name":"Pandavan Rock",
              "id":"KLA3",
              "pincode":[
                {
                  "pc":"524003"
                }
              ]
            },
            {
              "name":"Cherthala",
              "id":"KLA4",
              "pincode":[
                {
                  "pc":"524009"
                },
                {
                  "pc":"524011"
                }
              ]
            }
          ]
        },
        {
          "name":"Trivandrum",
          "id":"kl4",
          "areas":[
            {
              "name":"Varkala",
              "id":"KLT1",
              "pincode":[
                {
                  "pc":"525075"
                },
                {
                  "pc":"525076"
                },
                {
                  "pc":"525077"
                }
              ]
            },
            {
              "name":"Neyyattinkara",
              "id":"KLT2",
              "pincode":[
                {
                  "pc":"525009"
                },
                {
                  "pc":"525011"
                },
                {
                  "pc":"525012"
                },
                {
                  "pc":"525015"
                }
              ]
            },
            {
              "name":"Kattakada",
              "id":"KLT3",
              "pincode":[
                {
                  "pc":"525003"
                }
              ]
            },
            {
              "name":"Kovalam",
              "id":"KLT4",
              "pincode":[
                {
                  "pc":"525009"
                },
                {
                  "pc":"525011"
                }
              ]
            }
          ]
        },
        {
          "name":"Kollam",
          "id":"kl5",
          "areas":[
            {
              "name":"Perinad",
              "id":"KLK1",
              "pincode":[
                {
                  "pc":"541075"
                },
                {
                  "pc":"541076"
                },
                {
                  "pc":"541077"
                }
              ]
            },
            {
              "name":"Panayam",
              "id":"KLK2",
              "pincode":[
                {
                  "pc":"541009"
                },
                {
                  "pc":"541011"
                },
                {
                  "pc":"541012"
                },
                {
                  "pc":"541015"
                }
              ]
            },
            {
              "name":"Mulavana",
              "id":"KLK3",
              "pincode":[
                {
                  "pc":"541003"
                }
              ]
            },
            {
              "name":"East Kallada",
              "id":"KLK4",
              "pincode":[
                {
                  "pc":"541009"
                },
                {
                  "pc":"541011"
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "statename":"Karnataka",
      "id":"3",
      "cities":[
        {
          "name":"Bangalore",
          "id":"tn1",
          "areas":[
            {
              "name":"AnnaNagar",
              "id":"C1",
              "pincode":[
                {
                  "pc":"600075"
                },
                {
                  "pc":"600076"
                },
                {
                  "pc":"600077"
                }
              ]
            },
            {
              "name":"KKNagar",
              "id":"C2",
              "pincode":[
                {
                  "pc":"600109"
                },
                {
                  "pc":"600111"
                },
                {
                  "pc":"600112"
                },
                {
                  "pc":"600115"
                }
              ]
            },
            {
              "name":"T-Nagar",
              "id":"C3",
              "pincode":[
                {
                  "pc":"600003"
                }
              ]
            },
            {
              "name":"BesantNagar",
              "id":"C4",
              "pincode":[
                {
                  "pc":"600109"
                },
                {
                  "pc":"600111"
                }
              ]
            }
          ]
        },
        {
          "name":"Mysore",
          "id":"tn2",
          "areas":[
            {
              "name":"BigBazaarStreet",
              "id":"T1",
              "pincode":[
                {
                  "pc":"617075"
                },
                {
                  "pc":"617076"
                },
                {
                  "pc":"617077"
                }
              ]
            },
            {
              "name":"KKNagar",
              "id":"T2",
              "pincode":[
                {
                  "pc":"617109"
                },
                {
                  "pc":"617111"
                },
                {
                  "pc":"617112"
                },
                {
                  "pc":"617115"
                }
              ]
            },
            {
              "name":"Thurayur",
              "id":"T3",
              "pincode":[
                {
                  "pc":"617003"
                }
              ]
            },
            {
              "name":"Manaparai",
              "id":"T4",
              "pincode":[
                {
                  "pc":"617109"
                },
                {
                  "pc":"617111"
                }
              ]
            }
          ]
        },
        {
          "name":"Bhadravathi",
          "id":"tn3",
          "areas":[
            {
              "name":"EastGovindapuram",
              "id":"D1",
              "pincode":[
                {
                  "pc":"624075"
                },
                {
                  "pc":"624076"
                },
                {
                  "pc":"624077"
                }
              ]
            },
            {
              "name":"R.M.Colony",
              "id":"D2",
              "pincode":[
                {
                  "pc":"624009"
                },
                {
                  "pc":"624011"
                },
                {
                  "pc":"624012"
                },
                {
                  "pc":"624015"
                }
              ]
            },
            {
              "name":"SocietyStreet",
              "id":"D3",
              "pincode":[
                {
                  "pc":"624003"
                }
              ]
            },
            {
              "name":"ArivuThiruKovil",
              "id":"D4",
              "pincode":[
                {
                  "pc":"624009"
                },
                {
                  "pc":"624011"
                }
              ]
            }
          ]
        },
        {
          "name":"Coorg",
          "id":"tn4",
          "areas":[
            {
              "name":"MeenakshiStreet",
              "id":"M1",
              "pincode":[
                {
                  "pc":"625075"
                },
                {
                  "pc":"625076"
                },
                {
                  "pc":"625077"
                }
              ]
            },
            {
              "name":"Vilakuthoon",
              "id":"M2",
              "pincode":[
                {
                  "pc":"625009"
                },
                {
                  "pc":"625011"
                },
                {
                  "pc":"625012"
                },
                {
                  "pc":"625015"
                }
              ]
            },
            {
              "name":"Paravai",
              "id":"M3",
              "pincode":[
                {
                  "pc":"625003"
                }
              ]
            },
            {
              "name":"Samayanallur",
              "id":"M4",
              "pincode":[
                {
                  "pc":"625009"
                },
                {
                  "pc":"625011"
                }
              ]
            }
          ]
        },
        {
          "name":"Ballari",
          "id":"tn5",
          "areas":[
            {
              "name":"SaiBabaColony",
              "id":"CO1",
              "pincode":[
                {
                  "pc":"641075"
                },
                {
                  "pc":"641076"
                },
                {
                  "pc":"641077"
                }
              ]
            },
            {
              "name":"Saravanampatti",
              "id":"CO2",
              "pincode":[
                {
                  "pc":"641009"
                },
                {
                  "pc":"641011"
                },
                {
                  "pc":"641012"
                },
                {
                  "pc":"641015"
                }
              ]
            },
            {
              "name":"Kuniyamuthur",
              "id":"CO3",
              "pincode":[
                {
                  "pc":"641003"
                }
              ]
            },
            {
              "name":"B.K.Pudhur",
              "id":"CO4",
              "pincode":[
                {
                  "pc":"641009"
                },
                {
                  "pc":"641011"
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "statename":"AndhraPradesh",
      "id":"4",
      "cities":[
        {
          "name":"Chennai",
          "id":"tn1",
          "areas":[
            {
              "name":"AnnaNagar",
              "id":"C1",
              "pincode":[
                {
                  "pc":"600075"
                },
                {
                  "pc":"600076"
                },
                {
                  "pc":"600077"
                }
              ]
            },
            {
              "name":"KKNagar",
              "id":"C2",
              "pincode":[
                {
                  "pc":"600109"
                },
                {
                  "pc":"600111"
                },
                {
                  "pc":"600112"
                },
                {
                  "pc":"600115"
                }
              ]
            },
            {
              "name":"T-Nagar",
              "id":"C3",
              "pincode":[
                {
                  "pc":"600003"
                }
              ]
            },
            {
              "name":"BesantNagar",
              "id":"C4",
              "pincode":[
                {
                  "pc":"600109"
                },
                {
                  "pc":"600111"
                }
              ]
            }
          ]
        },
        {
          "name":"Trichy",
          "id":"tn2",
          "areas":[
            {
              "name":"BigBazaarStreet",
              "id":"T1",
              "pincode":[
                {
                  "pc":"617075"
                },
                {
                  "pc":"617076"
                },
                {
                  "pc":"617077"
                }
              ]
            },
            {
              "name":"KKNagar",
              "id":"T2",
              "pincode":[
                {
                  "pc":"617109"
                },
                {
                  "pc":"617111"
                },
                {
                  "pc":"617112"
                },
                {
                  "pc":"617115"
                }
              ]
            },
            {
              "name":"Thurayur",
              "id":"T3",
              "pincode":[
                {
                  "pc":"617003"
                }
              ]
            },
            {
              "name":"Manaparai",
              "id":"T4",
              "pincode":[
                {
                  "pc":"617109"
                },
                {
                  "pc":"617111"
                }
              ]
            }
          ]
        },
        {
          "name":"Dindigul",
          "id":"tn3",
          "areas":[
            {
              "name":"EastGovindapuram",
              "id":"D1",
              "pincode":[
                {
                  "pc":"624075"
                },
                {
                  "pc":"624076"
                },
                {
                  "pc":"624077"
                }
              ]
            },
            {
              "name":"R.M.Colony",
              "id":"D2",
              "pincode":[
                {
                  "pc":"624009"
                },
                {
                  "pc":"624011"
                },
                {
                  "pc":"624012"
                },
                {
                  "pc":"624015"
                }
              ]
            },
            {
              "name":"SocietyStreet",
              "id":"D3",
              "pincode":[
                {
                  "pc":"624003"
                }
              ]
            },
            {
              "name":"ArivuThiruKovil",
              "id":"D4",
              "pincode":[
                {
                  "pc":"624009"
                },
                {
                  "pc":"624011"
                }
              ]
            }
          ]
        },
        {
          "name":"Madurai",
          "id":"tn4",
          "areas":[
            {
              "name":"MeenakshiStreet",
              "id":"M1",
              "pincode":[
                {
                  "pc":"625075"
                },
                {
                  "pc":"625076"
                },
                {
                  "pc":"625077"
                }
              ]
            },
            {
              "name":"Vilakuthoon",
              "id":"M2",
              "pincode":[
                {
                  "pc":"625009"
                },
                {
                  "pc":"625011"
                },
                {
                  "pc":"625012"
                },
                {
                  "pc":"625015"
                }
              ]
            },
            {
              "name":"Paravai",
              "id":"M3",
              "pincode":[
                {
                  "pc":"625003"
                }
              ]
            },
            {
              "name":"Samayanallur",
              "id":"M4",
              "pincode":[
                {
                  "pc":"625009"
                },
                {
                  "pc":"625011"
                }
              ]
            }
          ]
        },
        {
          "name":"Coimbatore",
          "id":"tn5",
          "areas":[
            {
              "name":"SaiBabaColony",
              "id":"CO1",
              "pincode":[
                {
                  "pc":"641075"
                },
                {
                  "pc":"641076"
                },
                {
                  "pc":"641077"
                }
              ]
            },
            {
              "name":"Saravanampatti",
              "id":"CO2",
              "pincode":[
                {
                  "pc":"641009"
                },
                {
                  "pc":"641011"
                },
                {
                  "pc":"641012"
                },
                {
                  "pc":"641015"
                }
              ]
            },
            {
              "name":"Kuniyamuthur",
              "id":"CO3",
              "pincode":[
                {
                  "pc":"641003"
                }
              ]
            },
            {
              "name":"B.K.Pudhur",
              "id":"CO4",
              "pincode":[
                {
                  "pc":"641009"
                },
                {
                  "pc":"641011"
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "statename":"Punjab",
      "id":"5",
      "cities":[
        {
          "name":"Chennai",
          "id":"tn1",
          "areas":[
            {
              "name":"AnnaNagar",
              "id":"C1",
              "pincode":[
                {
                  "pc":"600075"
                },
                {
                  "pc":"600076"
                },
                {
                  "pc":"600077"
                }
              ]
            },
            {
              "name":"KKNagar",
              "id":"C2",
              "pincode":[
                {
                  "pc":"600109"
                },
                {
                  "pc":"600111"
                },
                {
                  "pc":"600112"
                },
                {
                  "pc":"600115"
                }
              ]
            },
            {
              "name":"T-Nagar",
              "id":"C3",
              "pincode":[
                {
                  "pc":"600003"
                }
              ]
            },
            {
              "name":"BesantNagar",
              "id":"C4",
              "pincode":[
                {
                  "pc":"600109"
                },
                {
                  "pc":"600111"
                }
              ]
            }
          ]
        },
        {
          "name":"Trichy",
          "id":"tn2",
          "areas":[
            {
              "name":"BigBazaarStreet",
              "id":"T1",
              "pincode":[
                {
                  "pc":"617075"
                },
                {
                  "pc":"617076"
                },
                {
                  "pc":"617077"
                }
              ]
            },
            {
              "name":"KKNagar",
              "id":"T2",
              "pincode":[
                {
                  "pc":"617109"
                },
                {
                  "pc":"617111"
                },
                {
                  "pc":"617112"
                },
                {
                  "pc":"617115"
                }
              ]
            },
            {
              "name":"Thurayur",
              "id":"T3",
              "pincode":[
                {
                  "pc":"617003"
                }
              ]
            },
            {
              "name":"Manaparai",
              "id":"T4",
              "pincode":[
                {
                  "pc":"617109"
                },
                {
                  "pc":"617111"
                }
              ]
            }
          ]
        },
        {
          "name":"Dindigul",
          "id":"tn3",
          "areas":[
            {
              "name":"EastGovindapuram",
              "id":"D1",
              "pincode":[
                {
                  "pc":"624075"
                },
                {
                  "pc":"624076"
                },
                {
                  "pc":"624077"
                }
              ]
            },
            {
              "name":"R.M.Colony",
              "id":"D2",
              "pincode":[
                {
                  "pc":"624009"
                },
                {
                  "pc":"624011"
                },
                {
                  "pc":"624012"
                },
                {
                  "pc":"624015"
                }
              ]
            },
            {
              "name":"SocietyStreet",
              "id":"D3",
              "pincode":[
                {
                  "pc":"624003"
                }
              ]
            },
            {
              "name":"ArivuThiruKovil",
              "id":"D4",
              "pincode":[
                {
                  "pc":"624009"
                },
                {
                  "pc":"624011"
                }
              ]
            }
          ]
        },
        {
          "name":"Madurai",
          "id":"tn4",
          "areas":[
            {
              "name":"MeenakshiStreet",
              "id":"M1",
              "pincode":[
                {
                  "pc":"625075"
                },
                {
                  "pc":"625076"
                },
                {
                  "pc":"625077"
                }
              ]
            },
            {
              "name":"Vilakuthoon",
              "id":"M2",
              "pincode":[
                {
                  "pc":"625009"
                },
                {
                  "pc":"625011"
                },
                {
                  "pc":"625012"
                },
                {
                  "pc":"625015"
                }
              ]
            },
            {
              "name":"Paravai",
              "id":"M3",
              "pincode":[
                {
                  "pc":"625003"
                }
              ]
            },
            {
              "name":"Samayanallur",
              "id":"M4",
              "pincode":[
                {
                  "pc":"625009"
                },
                {
                  "pc":"625011"
                }
              ]
            }
          ]
        },
        {
          "name":"Coimbatore",
          "id":"tn5",
          "areas":[
            {
              "name":"SaiBabaColony",
              "id":"CO1",
              "pincode":[
                {
                  "pc":"641075"
                },
                {
                  "pc":"641076"
                },
                {
                  "pc":"641077"
                }
              ]
            },
            {
              "name":"Saravanampatti",
              "id":"CO2",
              "pincode":[
                {
                  "pc":"641009"
                },
                {
                  "pc":"641011"
                },
                {
                  "pc":"641012"
                },
                {
                  "pc":"641015"
                }
              ]
            },
            {
              "name":"Kuniyamuthur",
              "id":"CO3",
              "pincode":[
                {
                  "pc":"641003"
                }
              ]
            },
            {
              "name":"B.K.Pudhur",
              "id":"CO4",
              "pincode":[
                {
                  "pc":"641009"
                },
                {
                  "pc":"641011"
                }
              ]
            }
          ]
        }
      ]
    }
  ]
 };
}